---
title: "Supplementary Figure 1. Forest plot of Cox Proportional Hazards model"
author: "Rebecca Hoyd"
date: "9/3/2021"
edits : "Malven - Jan 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(survival)
library(survminer)
library(ggplot2)
library(tibble)
library(tidyr)
library(Hmisc)
library(ggforce)
library(forcats)
```

# Functions

```{r}
extract_coxph_results <- function(cp.form, dattab){
    tmp <- coxph(as.formula(cp.form), data = dattab) %>%
      summary()
  pvals <- tmp$coefficients %>%
    as.data.frame() %>%
    rownames_to_column(var = "term") %>%
    mutate(p.value = `Pr(>|z|)`) %>%
    select(term, p.value)
  conf.int <- tmp$conf.int %>%
    as.data.frame() %>%
    rownames_to_column(var = "term") %>%
    mutate(hazard.ratio = `exp(coef)`,
           confint.low = `lower .95`,
           confint.high = `upper .95`) %>%
    select(term, hazard.ratio, confint.low, confint.high) %>%
    left_join(pvals) 
  return(conf.int)
}
```

# Load data
```{r}
data.dir <- "/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021"

clin <- read.csv(file.path(data.dir, "7-15-2021_tcga_clinical.csv"), stringsAsFactors = F)
exora <- read.csv(file.path(data.dir, "7-15-2021_tcga_exora-with-taxonomy.csv"), stringsAsFactors = F)

rarprev <- read.csv("../data/rarefied-prevalence_all-TCGA-samps.csv")
```

# Survival

```{r}
surv.in <- clin %>%
  dplyr::rename("sample" = "file_id.BAM") %>%
  inner_join(rarprev) %>%
  mutate(smoking = ifelse(pack_years_smoked >= 10, 1, 0),
         smoking = ifelse(is.na(smoking), 0, smoking),
         age = age_at_diagnosis/365.25,
         days = coalesce(days_to_death, days_to_last_follow_up),
         vitalstatus = ifelse(vital_status == "Dead", 1, 0),
         survstage = ifelse(grepl("IV", ajcc_clinical_stage), "Stage IV", ajcc_clinical_stage)) %>%
  drop_na(days, vitalstatus)
```

```{r}
alphapap.mod <- survfit(Surv(days, vitalstatus) ~ Alphapapillomavirus.9, data = surv.in)
alphapap.cox <- extract_coxph_results("Surv(days, vitalstatus) ~ Alphapapillomavirus.9 + smoking + age + survstage",
                                      surv.in)

alphapap.cox %>%
  mutate(vargroup = ifelse(grepl("survstage", term), "Stage", capitalize(term)),
         term = capitalize(gsub("survstage", "", term)),
         term = fct_relevel(term, "Alphapapillomavirus.9", after = 5)) %>%
  ggplot(aes(x = term, xend = term)) +
  geom_point(aes(y = hazard.ratio)) +
  geom_segment(aes(y = confint.low, yend = confint.high)) +
  labs(x = "", y = "Hazard Ratio") + 
  coord_flip() +
  geom_hline(yintercept = 1, lty = 2) +
  theme_bw()

ggsave("../figures/supp1_exorien_forestplot.png", width = 5, height = 5, dpi = 300)
```
