---
title: "surv volcano"
author: "Caroline Wheeler"
date: "4/6/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

```{r}
surv.res <- read.csv("../data/survival_multivar-microbes_genus_filtered.csv", stringsAsFactors = F)

data.dir <- "/fs/ess/PAS1695/projects/HNSC/data/drake-output/7-15-2021"

krakenmet <- read.delim("/fs/ess/PAS1695/exoticpipe/external-data/kraken2-metaphlan-taxonomy.txt",
                         header = F, stringsAsFactors = F) %>%
    rename("Taxonomy" = "V1")
```

```{r}
taxkey <- krakenmet %>%
  dplyr::filter(grepl("s__", Taxonomy)) %>%
  mutate(microbe = gsub(".*s__(.*)", "\\1", Taxonomy),
          microbe = make.names(microbe)) %>%
  select(microbe, Taxonomy)

taxkey <- taxkey %>%
  mutate(domain = gsub("(d__\\w+).*", "\\1", Taxonomy),
           term = ifelse(grepl("g__", Taxonomy),gsub(".*(g__\\w+).*", "\\1", Taxonomy), NA)) %>%
  mutate(term = ifelse(is.na(term), paste0("g__unclassified_", microbe), term)) %>%
  select(domain, term) %>%
  distinct()
```

```{r}
surv.plotin <- merge(surv.res, taxkey) %>%
  mutate(nlogp = -log(p.value),
         logHR = log(hazard.ratio),
         alphapap = term == "g__Alphapapillomavirus") %>%
  dplyr::filter(confint.high < Inf | confint.low > 0) %>%
  mutate(microbe = term)
```

```{r}
surv.plotin %>%
  ggplot(aes(x = logHR, y = nlogp, color = domain, size = alphapap, shape = alphapap, alpha = alphapap)) +
  geom_point() +
  geom_hline(yintercept = -log(0.05), lty = 2) +
  geom_vline(xintercept = 0, lty = 2) +
  scale_color_brewer(palette = "Set1") +
  scale_shape_manual(breaks = c(F,T), values = c(20, 18)) +
  scale_alpha_manual(values = c(.5,1)) +
  labs(x = "log(HR)", y = "-log(p.value)") +
  guides(size = FALSE, shape = FALSE, alpha = FALSE) +
  theme_bw() 

ggsave("../figures/volcano_survival-multivariate_genus.png")
```


